name: clang-tidy-review

# You can be more specific, but it currently only works on pull requests
on:
  pull_request:
    branches: [ main ]

jobs:
  tidy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Optionally generate compile_commands.json

    - uses: ZedThree/clang-tidy-review@v0.8.2
      id: review
      with:
        config_file: '.clang-tidy'
        clang_tidy_version: '12'
        exclude: "tests/*, googletest/*"
    # If there are any comments, fail the check
    - if: steps.review.outputs.total_comments > 0
      run: exit 1
