name: Run clang-format Linter

on: [pull_request]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.14
      with:
        source: './srcs'
        extensions: 'h,cpp,c,hpp'
        clangFormatVersion: 14
