name: Run clang-format Linter

on:
  pull_request:
    types: [ review_requested ]
    branches: [ main ]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.13
      with:
        source: './srcs'
        extensions: 'h,cpp,c,hpp'
        clangFormatVersion: 13
