name: clang-tidy-review

# You can be more specific, but it currently only works on pull requests
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Optionally generate compile_commands.json
    - uses: kohkubo/clang-tidy-review@v0.8.5
      id: review
      with:
        config_file: '.clang-tidy'
        include: "./srcs/"
        exclude: "googletest/**"
    # If there are any comments, fail the check
    - if: steps.review.outputs.total_comments > 0
      run: exit 1