name: C/C++ CI

on: [pull_request]

jobs:
  gtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: make_test
        run: |
          make -m
          make -C ./googletest
          cd ./googletest
          ./tester

  itest_all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: make_itest_all
        run: make itest_all

  gotest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: make_gotest
        run: make gotest
