name: C/C++ CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make -m

  gtest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: make_test
      run: make test

  gtest_mac:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v3
    - name: make_test_mac
      run: make test

  wtest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: make_wtest
      run: make wtest