name: C/C++ CI

on:
  pull_request:
    branches: [ main ]

jobs:
  gtest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: make_test
      run: |
        make -m
        make -C ./googletest
        cd ./googletest
        ./tester

  itest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: make_itest
      run: make itest
