name: C/C++ CI

on: [pull_request]

jobs:
  gtest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: make_test
      run: |
        make -m
        make -C ./googletest
        cd ./googletest
        ./tester

  itest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: make_itest
      run: make itest

  shell_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: shell_test
      run: bash test.sh
